apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-react-todo
  labels:
    app: app-react-todo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-react-todo
  template:
    metadata:
      labels:
        app: app-react-todo
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: eks-devops
          image: 639962416620.dkr.ecr.us-east-2.amazonaws.com/m2i-react-app-todo:latest
          imagePullPolicy: "Always"
          ports:
            - containerPort: 80
--- 
apiVersion: v1
kind: Service
metadata:
  labels:
    app: app-react-todo
  name: app-react-todo-service
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /
spec:
  type: NodePort
  selector:
    app: app-react-todo
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30007